FROM python:3.12.6-bullseye

RUN apt update && apt install git

WORKDIR /usr/src/app

COPY . .

WORKDIR /usr/src/app/backend

RUN pip install --no-cache-dir -r requirements.txt  

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]