services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
