FROM node:22.9-alpine3.20

WORKDIR /usr/src/app

RUN apk upgrade && apk add git

COPY . .

WORKDIR /usr/src/app/frontend

RUN npm install

RUN npm install -g @angular/cli

EXPOSE 4200
CMD ["npm", "run", "start"]