services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/frontend/node_modules
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
