services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/frontend/node_modules
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app/
    networks:
      - app-network
  
  mongodb:
    image: mongodb/mongodb-community-server:7.0.2-ubi9
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      -  /data/db:/data/db

networks:
  app-network:
    driver: bridge

