services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
